batch_size: 64
epochs: &epoch_number 500
optim: "adam"
lr: 0.001
min_lr: 1e-6
weight_decay: 1e-6
weight_decay_end: 0.4
warmup_epochs: 10
clip_grad: 3.0
use_lr_scheduler: True
use_wd_scheduler: True

seed: 42
log_level: "INFO"
fine_tune_from: null

save_every_n_epochs: *epoch_number
embed_vis_every_n_epochs: 50
visualize_attention: False
imgs_to_visualize: 5

# SelfClean: Normalizing
apply_l2_norm: False

model:
    base_model: "vit_tiny"
    model_type: "VIT"
    emb_dim: 192 # tiny: 192, small: 384, base: 768, rn18: 512, rn50: 1024
    encoder:
        # ResNet config
        out_dim: 128
        weights: "IMAGENET1K_V1"
        # ViT config
        patch_size: 16
        drop_path_rate: 0.1
    eval:
        n_last_blocks: 1
        avgpool_patchtokens: False

dataset:
    train_path: "data/DermaCompass/"
    val_size: 0.2
    loader:
        num_workers: 10
        drop_last: True
        pin_memory: True
    val_loader:
        num_workers: 10
        drop_last: False
        pin_memory: True
        shuffle: False
    multi_crop: True
    augmentations:
        gaussian_kernel: 23
        scaling: 1
        global_crops_scale: (0.7, 1.)
        local_crops_scale: (0.05, 0.4)
        global_crops_number: 2
        local_crops_number: 12
        global_crops_size: 224 # Normal ViT: 224, DINOv2(14patches): 196
        local_crops_size: 96 # Normal ViT: 96, DINOv2(14patches): 84
        remove_all_augmentation: True

loss:
    temperature: 0.5
    use_cosine_similarity: True
